### ISSUE TITLE
Package all schemas

### ISSUE THREAD

**Issue by wiese** [ioki-mobility/transitland-gql-client#96]
The schema is now distributed across 4 files ([here ff.](https://github.com/ioki-mobility/transitland-gql-client/blob/83603aff1abb05dcee10fd69ea8ef17eed2ad5dc/package.json#L25)), yet we are only publishing one (`schema.graphql`). We should release a new version which contains all of them (dist).

Copy happens here.
https://github.com/ioki-mobility/transitland-gql-client/blob/83603aff1abb05dcee10fd69ea8ef17eed2ad5dc/package.json#L31

**Comment by boredland** [comment]
this might be a wrong assumption: genql bundles up [all files into one](https://github.com/ioki-mobility/transitland-gql-client/blob/main/genql.ts#L10). and writes it out [into one](https://github.com/ioki-mobility/transitland-gql-client/blob/main/src/_client/schema.graphql) subsequently - the one we package later.

**Comment by wiese** [comment]
Happy to be wrong here if it means everything is all right.

**Comment by boredland** [comment]
ya, I think I just have been confused.
